# Generated by Django 4.2.13 on 2026-05-26 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Fuel & Procurement (ALV CSV)'), ('UTILITY', 'Utility Electricity (Portal CSV)'), ('TRAVEL', 'Corporate Travel (Concur/Navan CSV)')], max_length=20)),
                ('filename', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial (some rows failed)')], default='PENDING', max_length=20)),
                ('row_count', models.IntegerField(default=0, help_text='Total rows in file (excl. header)')),
                ('success_count', models.IntegerField(default=0, help_text='Rows that produced a record')),
                ('error_count', models.IntegerField(default=0, help_text='Rows that failed to parse')),
                ('warning_count', models.IntegerField(default=0, help_text='Records with quality flags')),
                ('processing_log', models.JSONField(default=list)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.organization')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1 — Direct emissions'), (2, 'Scope 2 — Purchased energy'), (3, 'Scope 3 — Value chain')])),
                ('category', models.CharField(choices=[('stationary_combustion', 'Stationary Combustion (Boilers, generators)'), ('mobile_combustion', 'Mobile Combustion (Fleet vehicles)'), ('purchased_electricity', 'Purchased Electricity'), ('business_travel_air', 'Business Travel — Air'), ('business_travel_hotel', 'Business Travel — Hotel/Accommodation'), ('business_travel_ground', 'Business Travel — Ground (Car/Taxi)'), ('business_travel_rail', 'Business Travel — Rail')], max_length=60)),
                ('activity_description', models.CharField(max_length=500)),
                ('activity_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('activity_unit', models.CharField(max_length=50)),
                ('activity_value_normalized', models.DecimalField(decimal_places=4, max_digits=18)),
                ('activity_unit_normalized', models.CharField(max_length=50)),
                ('emission_factor', models.DecimalField(decimal_places=6, max_digits=15)),
                ('emission_factor_unit', models.CharField(max_length=100)),
                ('emission_factor_source', models.CharField(max_length=400)),
                ('co2e_kg', models.DecimalField(decimal_places=4, max_digits=18)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('source_ref', models.CharField(help_text='Primary key in the source system: SAP doc no, meter ID, Concur trip ID', max_length=400)),
                ('raw_data', models.JSONField(help_text='Verbatim CSV row dict as ingested. Immutable — never written after creation.')),
                ('warnings', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('flagged', 'Flagged'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('review_note', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edit_history', models.JSONField(default=list)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.ingestionjob')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='accounts.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start', 'scope', 'category'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('ingested', 'Ingested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged'), ('pending', 'Reset to Pending'), ('edited', 'Edited'), ('locked', 'Locked for Audit'), ('note_added', 'Note Added')], max_length=20)),
                ('actor_name', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('data_before', models.JSONField(blank=True, null=True)),
                ('data_after', models.JSONField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='ingestion.emissionrecord')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['org', 'status'], name='ingestion_e_org_id_2f09ae_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['org', 'scope'], name='ingestion_e_org_id_41f467_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['org', 'period_start', 'period_end'], name='ingestion_e_org_id_f5e9b3_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['job'], name='ingestion_e_job_id_7fc271_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['is_locked'], name='ingestion_e_is_lock_756632_idx'),
        ),
    ]
